name: Lint

on: [push]

jobs:
  golang-ci-lint:
    name: Lint the project using GolangCI Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1
